site_name: Î»ORM Wiki
docs_dir: docs
site_dir: wiki
theme:
  name: readthedocs

nav:
  - Home: index.html
  - Usage: Usage/index.html
  - Features: Features/index.html
  - Api: api/index.html
  - Cli: cli/index.html
  - Labs: https://github.com/lambda-orm/lambdaorm-labs
  - Queries:
      - Query Language: queries/Query-Language/index.html
      - Expression: queries/Expression/index.html
      - Select: queries/dql/Select/index.html
      - Join: queries/dql/Join/index.html
      - Grouping: queries/dql/Grouping/index.html
      - Include: queries/dql/Include/index.html
      - Insert: queries/dml/Insert/index.html
      - Bulk Insert: queries/dml/BulkInsert/index.html
      - Update: queries/dml/Update/index.html
      - Delete: queries/dml/Delete/index.html      
  - Schema:
      - Definition: schema/Definition/SchemaDefinition/index.html
      - Expressions: schema/Definition/SchemaDefinition-Expressions/index.html
      - Environment Variables: schema/Definition/SchemaDefinition-EnvironmentVariables/index.html
      - Composite: schema/Definition/SchemaDefinition-Composite/index.html
      - Listeners: schema/Examples/SchemaExample-Listener/index.html
      - Basic:  schema/Examples/SchemaExample-Basic/index.html
      - Extend Entity:  schema/Examples/SchemaExample-Extend/index.html
      - Multiples Stages:  schema/Examples/SchemaExample-MultiplesStages/index.html
      - Stage with Multiples Sources:  schema/Examples/SchemaExample-StageMultiplesSources/index.html
      - Entity Composite:  schema/Examples/SchemaExample-Composite/index.html
      - Push: schema/Synchronization/SchemaSynchronization-Push/index.html
      - Pull: schema/Synchronization/SchemaSynchronization-Pull/index.html
      - Fetch: schema/Synchronization/SchemaSynchronization-Fetch/index.html
      - Introspect: schema/Synchronization/SchemaSynchronization-Introspect/index.html
      - Incorporate: schema/Synchronization/SchemaSynchronization-Incorporate/index.html
      - Use: schema/Schema-Use/index.html  
  - Repository: Repository/index.html
  - Transaction: Transaction/index.html
  - Usage: Usage/index.html
  - Change log: https://lambda-orm.github.io/wiki/CHANGELOG/index.html