site_name: Î»ORM Wiki
docs_dir: docs
site_dir: wiki
theme:
  name: readthedocs
extra_css:
  - extra.css
extra_javascript:
  - extra.js
markdown_extensions:
  - toc:
      permalink: false
      toc_depth: 2

nav:
  - Home: /
  - Features: Features
  - Api: api
  - Cli: cli
  - Labs: https://github.com/lambda-orm/lambdaorm-labs
  - Queries:
      - Query Language: queries/Query-Language
      - Expression: queries/Expression
      - Select: queries/Select
      - Join: queries/Join
      - Grouping: queries/Grouping
      - Include: queries/Include
      - Insert: queries/Insert
      - Bulk Insert: queries/BulkInsert
      - Update: queries/Update
      - Delete: queries/Delete
      - Operators & Functions: queries/operatorsAndFunctions/OperatorsAndFunctions   
  - Schema:
      - Definition: schema/SchemaDefinition
      - Expressions: schema/SchemaDefinition-Expressions
      - Environment Variables: schema/SchemaDefinition-EnvironmentVariables
      - Composite: schema/SchemaDefinition-Composite
      - Listeners: schema/SchemaExample-Listener
      - Basic:  schema/SchemaExample-Basic
      - Extend Entity:  schema/SchemaExample-Extend
      - Multiples Stages:  schema/SchemaExample-MultiplesStages
      - Stage with Multiples Sources:  schema/SchemaExample-StageMultiplesSources
      - Entity Composite:  schema/SchemaExample-Composite
      - Push: schema/SchemaSynchronization-Push
      - Pull: schema/SchemaSynchronization-Pull
      - Fetch: schema/SchemaSynchronization-Fetch
      - Introspect: schema/SchemaSynchronization-Introspect
      - Incorporate: schema/SchemaSynchronization-Incorporate
      - Use: schema/Schema-Use
  - Usage:     
    - Repository: usage/Repository
    - Transaction: usage/Transaction
    - Usage: usage/Usage
    - Change log: usage/CHANGELOG