name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'   # no cache

      - name: Install MkDocs (+ tema si aplica)
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs
          # si usas Material:
          # pip install mkdocs-material

      - name: Build
        run: mkdocs build --clean

      - name: Upload artifact (site_dir)
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./wiki  # tu site_dir

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
